import type { Metadata } from "next";
import { Source_Sans_3 } from "next/font/google";
import "./globals.css";
import Header from "../components/header";
import Footer from "@/components/Footer";

const geistMono = Source_Sans_3({
  variable: "--font-Source-Sans-3-mono",
  subsets: ["latin"],
  weight: ["400", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Tatiana Portfolio",
  description: "Generated by Tatiana's Portfolio",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistMono.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <Header />
        </header>
        <main className="pt-16">
          {/* Espaço para o header fixo */}
          {children}
        </main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
